version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "alphabot/package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
          
      - run: cd alphabot && npm install
      
      
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "alphabot/package.json" }}
          
      - run: cd alphabot && npm test
      
  deploy-image:
    machine: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "5c:49:a6:a6:cf:c9:2e:ba:d5:3f:1b:7b:c9:53:7f:70"
      - run: 
          name: Deploy over SSH
          command: |
           ssh filip_777@34.89.247.185 "~/scripts/deploy.sh"        
workflows:
    build-and-test:
      jobs:
        - build-and-test
        - deploy-image:
            requires:
              - build-and-test